### ISSUE TITLE
README.md outdated

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-data-parser#10]
In the readme example code, this command:
`your_parser.extract_master_json()  # To get the master json`
should be this:
`your_parser.generate_master_json()  # To get the master json`

I'm not 100% sure that this should even be in the readme as the next command, "extract_media_locally" generates the master JSON along with extracting the rest of the course media from the source JSON.  The "generate_master_json" command only returns the JSON and does not write it to a file, so it almost seems unnecessary to include it.  Maybe we should remove that line entirely and update the comment on the "extract_media_locally" line to denote that the master JSON is extracted along with it?

**Comment by kyfantaz** [comment]
Closed by #11
