### ISSUE TITLE
parse instructor salutation field

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-data-parser#136]
We need the salutation field in order to build an appropriate instructor list. Currently, without the salutation we render everyone's name with a "Prof." which is incorrect. 

The field was missing from the raw JSON export. It was [added in this PR](https://github.com/mitocw/ocwcms/pull/243), but the new data only appears in one course so far: `8-01sc-classical-mechanics-fall-2016`. We haven't yet worked out how/if we will update the other ~2500 courses. 

Any solution should handle the case where the field exists, and where the field is absent.

**Comment by gumaerc** [comment]
@pdpinch I think this can just be closed, as the `instructors` array is pretty much copied verbatim.  If the `salutation` key is there, it will appear in the parsed JSON.  I've verified this in `open-learning-course-data-production` and the `salutation` key is there in 92 courses.  The only work necessary should be modifying `ocw-to-hugo` to incorporate it into the course data template.

**Comment by gumaerc** [comment]
this is now fixed and deployed to prod
