### ISSUE TITLE
Error parsing course data

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-data-parser#156]
If you parse one of
 - `res-cms-154-launching-innovation-in-schools-spring-2019`
 - `res-cms-501-envisioning-the-graduate-of-the-future-spring-2020`
 - `res-cms-503-becoming-a-more-equitable-educator-mindsets-and-practices-spring-2020`

You get `ValueError('not enough values to unpack (expected 2, got 1)')` on `ocw_data_parser.py:408` when it tries to split `ocw_feature_url` in `courselist_features`. I think it's probably just bad data but we should add some code to handle the exception more gracefully

**Comment by pdpinch** [comment]
These are all "shell" courses that (mostly) consist on an "Online Publication" external link. I don't know if that's related to the error, but they those external links need to be added to ocw-to-hugo manually. I'll open a PR for that.

**Comment by pdpinch** [comment]
This appears to be a course authoring error. Each of these legacy courses features a link to open learning library that isn't functioning correctly. 

For example on https://ocw.mit.edu/resources/res-cms-501-envisioning-the-graduate-of-the-future-spring-2020/index.htm, this link doesn't work:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/430126/133841653-9f31e278-0cc1-4887-aafb-0c2168c06b9f.png">

**Comment by pdpinch** [comment]
I saw you added a try/except block for extracting course features in #158. Do you expect that this will still fail, but raise an exception now? I'm still planning to ask the OCW team to fix these in plone (since they appear to be broken on the legacy site as well)

**Comment by noisecapella** [comment]
@pdpinch there should be a logged exception, logged to sentry whenever the next `backpopulate_ocw_data` task runs
