### ISSUE TITLE
Videos missing from 18.03sc, 9-00sc courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-data-parser#168]
There is at least one video missing from the parsed JSON for 18.023SC. 

On the legacy site, this video is displayed when clicking the link "separable equations" on https://ocw.mit.edu/courses/mathematics/18-03sc-differential-equations-fall-2011/unit-i-first-order-differential-equations/basic-de-and-separable-equations/

The link for this videos renders properly in nextgen at https://ocwnext.odl.mit.edu/courses/18-03sc-differential-equations-fall-2011/pages/unit-i-first-order-differential-equations/basic-de-and-separable-equations/ but it returns a 404 (equivalent) when clicked. 

In the raw json, there is a YouTube video `76WdBlGpxVw` described in the file at `s3://ocw-content-storage/PROD/18/18.029SC/Fall_2011/18-03sc-differential-equations-fall-2011/0/52.json to Fall_2011/18-03sc-differential-equations-fall-2011/0/52.json`

As far as I can tell, I don't see any corresponding data in the course repository, or in the parsed json at `s3://open-learning-course-data-production/18-02sc-multivariable-calculus-fall-2010/18-02sc-multivariable-calculus-fall-2010_parsed.json`

**Comment by pdpinch** [comment]
@mbertrand do you think https://github.com/mitodl/ocw-to-hugo/issues/459 will fix these two as well?

**Comment by mbertrand** [comment]
@pdpinch the video for 18-03 worked locally with the PR changes in place.  What is the misbehaving video for 900sc?

<img width="838" alt="Screen Shot 2022-03-01 at 8 27 54 AM" src="https://user-images.githubusercontent.com/187676/156178077-6e3baa16-d7b8-4bb0-b76a-35d269836a4f.png">

**Comment by pdpinch** [comment]
I haven't been able to find the 9.00sc video I had in mind, but @dseaton is qa'ing that course now. If he finds anything he'll let you know.

**Comment by pdpinch** [comment]
This is working now on RC:

https://ocwnext-rc.odl.mit.edu/courses/18-03sc-differential-equations-fall-2011/resources/separable-equations/

but not on ocwnext.odl.mit.edu. Maybe it needs a publish? I'll give it a shot. 

https://ocwnext.odl.mit.edu/courses/18-03sc-differential-equations-fall-2011/resources/separable-equations/

**Comment by pdpinch** [comment]
works now! 

https://ocwnext.odl.mit.edu/courses/18-03sc-differential-equations-fall-2011/resources/separable-equations/

**Comment by dseaton** [comment]
@pdpinch @mbertrand Sorry I am late to this. I only have notes for one video mishap in 9.00SC, but it's a malformed video resource link: https://ocwnext.odl.mit.edu/courses/9-00sc-introduction-to-psychology-fall-2011/pages/adult-development/
