### ISSUE TITLE
some videos missing their descriptions

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-data-parser#190]
### Steps to Reproduce

Parse a course that has a video description in the `text` property

### Expected Behavior

The video description is pulled in as the `text` property in parsed JSON

### Actual Behavior

The `text` property is left behind

**Comment by pdpinch** [comment]
for example, this video on the legacy site: /courses/aeronautics-and-astronautics/16-346-astrodynamics-fall-2008/video-lecture/
