### ISSUE TITLE
Missing videos in 18.01sc

### ISSUE THREAD

**Issue by dseaton** [mitodl/ocw-data-parser#193]
We have broken video links in 18.01sc that we think are due to missing video resources. For example, this page contains one working and one broken video clip link: [Studio Link](https://ocw-studio.odl.mit.edu/sites/18-01sc-single-variable-calculus-fall-2010/type/page/edit/625f9141-b9dc-5a93-65ac-ef497e19af09/?q=17), [NextGen Link](https://ocw-published.odl.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/pages/1.-differentiation/part-b-implicit-differentiation-and-inverse-functions/session-17-the-exponential-function-its-derivative-and-its-inverse/).

As an author, if I try to replace the broken link text using the add link feature, I cannot find the video. You can see the working video on Old Gen [here](https://old.ocw.mit.edu/courses/mathematics/18-01sc-single-variable-calculus-fall-2010/1.-differentiation/part-b-implicit-differentiation-and-inverse-functions/session-17-the-exponential-function-its-derivative-and-its-inverse).

The same issue occurs in a number of other places that we know about.
* Session 18: [Studio Link](https://ocw-studio.odl.mit.edu/sites/18-01sc-single-variable-calculus-fall-2010/type/page/edit/0cf2fa75-aeb6-82db-f14c-169c98cd1a15/?q=18)
* Session 19: [Studio Link](https://ocw-studio.odl.mit.edu/sites/18-01sc-single-variable-calculus-fall-2010/type/page/edit/60442492-7fbe-5ea4-76fd-72662493105b/?q=19)

I'll keep adding examples, but this course has over 100 clips. One thing the team could use help with, is identifying these broken links.

**Comment by pdpinch** [comment]
@briangrossman ran a link check and it only turned up 8 URLs, 5 of which are videos, 3 of which are on one page. Not sure why that page was cursed. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/pdpinch/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/pdpinch/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



404 not found | https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/resources/clip-1-definition-of-ex/ | Clip 1:   Definition of ex | https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/pages/1.-differentiation/part-b-implicit-differentiation-and-inverse-functions/session-17-the-exponential-function-its-derivative-and-its-inverse/
-- | -- | -- | --
404 not found | https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/resources/clip-1-value-of-e/ | Clip 1: Value of e | https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/pages/1.-differentiation/part-b-implicit-differentiation-and-inverse-functions/session-19-an-interesting-limit-involving-e/
404 not found | https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/resources/clip-1-other-bases/ | Clip 1: Other Bases | https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/pages/1.-differentiation/part-b-implicit-differentiation-and-inverse-functions/session-18-derivatives-of-other-exponential-functions/
404 not found | https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/resources/clip-2-derivative-of-ax-logarithmic/ | Clip 2: Derivative of ax,   Logarithmic | https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/pages/1.-differentiation/part-b-implicit-differentiation-and-inverse-functions/session-18-derivatives-of-other-exponential-functions/
404 not found | https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/resources/clip-3-derivative-of-xx/ | Clip 3: Derivative of xx | https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/pages/1.-differentiation/part-b-implicit-differentiation-and-inverse-functions/session-18-derivatives-of-other-exponential-functions/



</body>

</html>

**Comment by pdpinch** [comment]
Perhaps https://github.com/mitodl/ocw-to-hugo/issues/459 has some relevant information about recovering lost videos.

**Comment by gumaerc** [comment]
I did some research on this today.  These videos are what are referred to in the legacy system as "embedded media."  In the parsed JSON, these are represented by a dictionary containing the video metadata, which contains another list of objects of different pieces of actual media related to the video like the youtube video itself, the thumbnail, internet archive, etc.

In `ocw-to-hugo`, we filter for video embedded media with the following:

```
    .filter(
      media =>
        media["embedded_media"].filter(embeddedMedia =>
          VIDEO_EMBEDDED_MEDIA_IDS.has(embeddedMedia["id"])
        ).length > 0
    )
```
...where `VIDEO_EMBEDDED_MEDIA_IDS` contains:
```
  VIDEO_EMBEDDED_MEDIA_IDS: new Set([
    "Video-YouTube-Stream",
    "Video-YouTube-MP4",
    "3Play-3PlayYouTubeid-Stream"
  ])
```

The issue seems to be that for some reason on these videos, the `id` property on the YouTube `embedded_media` item is `copy_of_Video-YouTube-Stream`.  I searched across all the parsed JSON and found 6 results for this ID across 2 courses.  All but 1 were in 18-01sc.  I'll make a quick PR in `ocw-to-hugo` to add `copy_of_Video-YouTube-Stream` to the `VIDEO_EMBEDDED_MEDIA_IDS` array so that these videos will automatically be picked up.  As far as importing them we might want to do that manually as there are so few of them, to avoid having to re-import those courses.

**Comment by pdpinch** [comment]
@gumaerc what remains to be done here?

**Comment by gumaerc** [comment]
@pdpinch The `ocw-to-hugo` PR was merged to bring the missing videos into `ocw-to-hugo-output` S3 buckets.  A migration needs to be written in `ocw-studio` to bring them in, because I'm imagining we don't want to re-import the affected courses at this point.

**Comment by gumaerc** [comment]
@dseaton I ran a management command in RC that should have pulled in the missing videos without overwriting anything else in the course.  Could you take a look at https://ocw-draft-qa.global.ssl.fastly.net/courses/18-01sc-single-variable-calculus-fall-2010/ and verify for me that everything is there as expected?  This video was pulled in, for example: https://ocw-draft-qa.global.ssl.fastly.net/courses/18-01sc-single-variable-calculus-fall-2010/resources/clip-1-definition-of-ex/

This Github commit shows what was added: https://github.mit.edu/ocw-content-rc/18.01sc-fall-2010/commit/741f084d8a56c20f895d15aba8ccb57732ef40e3

**Comment by dseaton** [comment]
Everything looks correct. I clicked through each of the urls originally provided, changed the base url to "fastly", and all the clips were present and starting from the correct time.

**Comment by gumaerc** [comment]
@dseaton The missing videos have been published live to production.  Once you've verified that everything looks good, go ahead and close this issue.

**Comment by dseaton** [comment]
Done.
