### ISSUE TITLE
Instructor insights section missing data

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-data-parser#21]
Some of the courses' "instructor insights" pages seem to be built in a different way.  Rather than the HTML for the page solely being stored in the "text" property, it seems to be spread out across a couple different ones.  For example:

- studentinformationtext
- curriculuminformationtext
- courseteamrolestext
- theclassroomtext
- howstudenttimewasspenttext
- courseoverviewtext
- ad_champion_text
- bottomtext
- courseoutcomestext
- instructorinsightstext

An example of such a course:

https://ocw.mit.edu/courses/civil-and-environmental-engineering/1-00-introduction-to-computers-and-engineering-problem-solving-spring-2012/instructor-insights/

A search across all OCW courses found this pattern in 229 of them, out of 3755.

**Comment by pdpinch** [comment]
@gumaerc can you give me an example of the "other" instructor insight format?

**Comment by gumaerc** [comment]
@pdpinch This course has all the content for the Instructor Insights section in the "text" field in its source JSON:

https://ocw.mit.edu/courses/aeronautics-and-astronautics/16-412j-cognitive-robotics-spring-2016/instructor-insights/
