### ISSUE TITLE
stop loading large binary files into memory

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-data-parser#7]
When running the parser as part of the open-discussions app, we are loading "foreign media" files into memory. Some of these files are greater than 2GB and the app server runs out of memory. 

Ideally, these files should be streamed or chunked in some way as to avoid going into memory. In the interests of time, we could also add a switch of some sort to skip "foreign media" over a certain size (or skip it altogether). 

> The ocw import keeps dying at the same point in ci and rc while uploading a 2G file to S3 (`MIT16_412S16_cognitive_robotics_student_vm.ova`), and apparently the ocw-parser loads it all into memory at once.  Works locally but my docker instance has 7GB memory available.  I ran it from the heroku shell to see what's going on and I get kicked right out of the shell during this upload.

**Comment by alizag** [comment]
[This commit](https://github.com/zagaran/ocw-data-parser/commit/294e00ee37ffb2b93e15b6439f10674ad4c9f46e) closes this issue
